{
 "title": "Cryostat Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Recording Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recording Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "source": "url",
     "target": "events.custom.recordingDuration",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"events.custom.recordingDuration\", \"type\": \"table\" }], \"range\": {\"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\"} }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Recording Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "source": "url",
     "target": "events.custom.startTime",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"events.custom.startTime\", \"type\": \"table\" }], \"range\": {\"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\"} }",
      "method": "POST"
     }
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "Cores", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.CPUInformation.cores",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"targets\":[{\"refId\":\"A\",\"target\":\"jdk.CPUInformation.cores\",\"type\":\"timeserie\"}],\"range\":{\"from\":\"${__timeFrom:date}\",\"to\":\"${__timeTo:date}\"}}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Hardware Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "Hardware Threads", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.CPUInformation.hwThreads",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"targets\":[{\"refId\":\"A\",\"target\":\"jdk.CPUInformation.hwThreads\",\"type\":\"timeserie\"}],\"range\":{\"from\":\"${__timeFrom:date}\",\"to\":\"${__timeTo:date}\"}}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Total Physical Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "Physical Memory Size", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.PhysicalMemory.totalSize",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"targets\":[{\"refId\":\"A\",\"target\":\"jdk.PhysicalMemory.totalSize\",\"type\":\"timeserie\"}],\"range\":{\"from\":\"${__timeFrom:date}\",\"to\":\"${__timeTo:date}\"}}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "jdk.CPULoad.jvmUser", "type": "number" },
      { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.CPULoad.jvmUser",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.CPULoad.jvmUser\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "0", "text": "jdk.CPULoad.jvmSystem", "type": "number" },
      { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.CPULoad.jvmSystem",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.CPULoad.jvmSystem\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
      "method": "POST"
     }
    },
    {
     "columns": [
      { "selector": "0", "text": "jdk.CPULoad.machineTotal", "type": "number" },
      { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.CPULoad.machineTotal",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"C\", \"target\": \"jdk.CPULoad.machineTotal\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Used Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "columns": [
      { "selector": "0", "text": "jdk.PhysicalMemory.usedSize", "type": "number" },
      { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
     ],
     "parser": "backend",
     "root_selector": "datapoints",
     "source": "url",
     "target": "jdk.PhysicalMemory.usedSize",
     "type": "json",
     "url": "/query",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.PhysicalMemory.usedSize\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.NetworkUtilization.readRate",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.NetworkUtilization.readRate",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.NetworkUtilization.readRate\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.NetworkUtilization.writeRate",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.NetworkUtilization.writeRate",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.NetworkUtilization.writeRate\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "columns": [
        { "selector": "0", "text": "jdk.FileRead", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.FileRead",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.FileRead\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        { "selector": "0", "text": "jdk.FileWrite", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.FileWrite",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.FileWrite\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Thread Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.JavaThreadStatistics.accumulatedCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.JavaThreadStatistics.accumulatedCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.JavaThreadStatistics.accumulatedCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.JavaThreadStatistics.activeCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.JavaThreadStatistics.activeCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.JavaThreadStatistics.activeCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.JavaThreadStatistics.daemonCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.JavaThreadStatistics.daemonCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"C\", \"target\": \"jdk.JavaThreadStatistics.daemonCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.JavaThreadStatistics.peakCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.JavaThreadStatistics.peakCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"D\", \"target\": \"jdk.JavaThreadStatistics.peakCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Thread Context Switch Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.ThreadContextSwitchRate.switchRate",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.ThreadContextSwitchRate.switchRate",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.ThreadContextSwitchRate.switchRate\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "columns": [
        { "selector": "0", "text": "jdk.GCHeapSummary.heapUsed", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.GCHeapSummary.heapUsed",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.GCHeapSummary.heapUsed\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Object Allocation Sample",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "parser": "simple",
       "source": "url",
       "target": "jdk.ObjectAllocationSample.weight?objectClass=*",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "text/plain",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.ObjectAllocationSample.weight?objectClass=*\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Safepoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "columns": [
        { "selector": "0", "text": "jdk.SafepointBegin.duration", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.SafepointBegin.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.SafepointBegin.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Metaspace Summary",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.metaspace:committed",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.metaspace:committed",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.MetaspaceSummary.metaspace:committed\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.metaspace:reserved",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.metaspace:reserved",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.MetaspaceSummary.metaspace:reserved\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.metaspace:used",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.metaspace:used",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"C\", \"target\": \"jdk.MetaspaceSummary.metaspace:used\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.dataSpace:committed",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.dataSpace:committed",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"D\", \"target\": \"jdk.MetaspaceSummary.dataSpace:committed\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.dataSpace:reserved",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.dataSpace:reserved",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"E\", \"target\": \"jdk.MetaspaceSummary.dataSpace:reserved\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceSummary.dataSpace:used",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceSummary.dataSpace:used",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"F\", \"target\": \"jdk.MetaspaceSummary.dataSpace:used\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Metaspace GC Threshold",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceGCThreshold.oldValue",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceGCThreshold.oldValue",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.MetaspaceGCThreshold.oldValue\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.MetaspaceGCThreshold.newValue",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.MetaspaceGCThreshold.newValue",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.MetaspaceGCThreshold.newValue\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Compiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compiler Peak Time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.peakTimeSpent",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.peakTimeSpent",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.CompilerStatistics.peakTimeSpent\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Compiler: Total Time Spent",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.totalTimeSpent",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.totalTimeSpent",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.CompilerStatistics.totalTimeSpent\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Compiler Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.compileCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.compileCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.CompilerStatistics.compileCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.bailoutCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.bailoutCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.CompilerStatistics.bailoutCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.invalidatedCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.invalidatedCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"C\", \"target\": \"jdk.CompilerStatistics.invalidatedCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.osrCompileCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.osrCompileCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"D\", \"target\": \"jdk.CompilerStatistics.osrCompileCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.CompilerStatistics.standardCompileCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.CompilerStatistics.standardCompileCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"E\", \"target\": \"jdk.CompilerStatistics.standardCompileCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ClassLoadingStatistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.ClassLoadingStatistics.unloadedClassCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.ClassLoadingStatistics.unloadedClassCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.ClassLoadingStatistics.unloadedClassCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.ClassLoadingStatistics.loadedClassCount",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.ClassLoadingStatistics.loadedClassCount",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"jdk.ClassLoadingStatistics.loadedClassCount\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Exception Statistics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "jdk.ExceptionStatistics.throwables",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "jdk.ExceptionStatistics.throwables",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"jdk.ExceptionStatistics.throwables\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Frameworks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quarkus REST Timeseries",
     "type": "xychart",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 27 },
     "targets": [
      {
       "columns": [
        { "selector": "0", "text": "duration", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"A\", \"target\": \"quarkus.Rest.duration\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      },
      {
       "columns": [
        { "selector": "0", "text": "resourceClass", "type": "string" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"B\", \"target\": \"quarkus.Rest.resourceClass\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      },
      {
       "columns": [
        { "selector": "0", "text": "resourceMethod", "type": "string" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"B\", \"target\": \"quarkus.Rest.resourceMethod\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Hibernate ORM",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "timeticks" } },
     "targets": [
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.CacheGet.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.CacheGet.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"A\", \"target\": \"org.hibernate.orm.CacheGet.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.CachePut.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.CachePut.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"B\", \"target\": \"org.hibernate.orm.CachePut.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.CollectionRecreateEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.CollectionRecreateEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"C\", \"target\": \"org.hibernate.orm.CollectionRecreateEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.CollectionRemoveEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.CollectionRemoveEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"D\", \"target\": \"org.hibernate.orm.CollectionRemoveEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.CollectionUpdateEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.CollectionUpdateEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"E\", \"target\": \"org.hibernate.orm.CollectionUpdateEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.DirtyCalculationEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.DirtyCalculationEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"F\", \"target\": \"org.hibernate.orm.DirtyCalculationEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.EntityDeleteEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.EntityDeleteEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"G\", \"target\": \"org.hibernate.orm.EntityDeleteEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.EntityInsertEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.EntityInsertEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"H\", \"target\": \"org.hibernate.orm.EntityInsertEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.EntityUpdateEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.EntityUpdateEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"I\", \"target\": \"org.hibernate.orm.EntityUpdateEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.EntityUpsertEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.EntityUpsertEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"J\", \"target\": \"org.hibernate.orm.EntityUpsertEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.FlushEvent.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.FlushEvent.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"K\", \"target\": \"org.hibernate.orm.FlushEvent.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      },
      {
       "columns": [
        {
         "selector": "0",
         "text": "org.hibernate.orm.JdbcBatchExecution.duration",
         "type": "number"
        },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "org.hibernate.orm.JdbcBatchExecution.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{ \"targets\": [{ \"refId\": \"L\", \"target\": \"org.hibernate.orm.JdbcBatchExecution.duration\", \"type\": \"timeserie\" }], \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" } }",
        "method": "POST"
       }
      }
     ]
    },
    {
     "title": "Quarkus REST Endpoint Statistics",
     "type": "table",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 38 },
     "targets": [
      {
       "columns": [
        { "selector": "0", "text": "duration", "type": "number" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"A\", \"target\": \"quarkus.Rest.duration\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      },
      {
       "columns": [
        { "selector": "0", "text": "resourceClass", "type": "string" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"B\", \"target\": \"quarkus.Rest.resourceClass\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      },
      {
       "columns": [
        { "selector": "0", "text": "resourceMethod", "type": "string" },
        { "selector": "1", "text": "timestamp", "type": "timestamp_epoch" }
       ],
       "parser": "backend",
       "root_selector": "datapoints",
       "source": "url",
       "target": "quarkus.Rest.duration",
       "type": "json",
       "url": "/query",
       "url_options": {
        "body_content_type": "application/json",
        "body_type": "raw",
        "data": "{\n  \"targets\": [\n    { \"refId\": \"B\", \"target\": \"quarkus.Rest.resourceMethod\", \"type\": \"timeserie\" }\n  ],\n  \"range\": { \"from\": \"${__timeFrom:date}\", \"to\": \"${__timeTo:date}\" }\n}",
        "method": "POST"
       }
      }
     ]
    }
   ]
  }
 ]
}